name: Yamdb_final

on: [push]

jobs:
  tests:
  # testing updated code by flake8 and pytest
    runs-on: ubuntu-20.04

    steps:
      - name: Pulling repo
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r api_yamdb/requirements.txt

      - name: Testing
        run: |
          python -m flake8

      - name: Testing with django tests
        run: |
          cd api_yamdb/
          python manage.py test
  build_and_push_2_dockerhub:
  # building the "web" image and push it to DockerHub for pulling it later
    runs-on: ubuntu-20.04

    needs: tests

    steps:
      - name: Pulling repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          context: ./api_yamdb/
          push: true
          tags: ${{secrets.HUB_USERNAME}}/web:v2