name: Yamdb_final

on: [push]

jobs:
  tests:
  # testing updated code by flake8 and pytest
    runs-on: ubuntu-20.04

    steps:
      - name: Pulling repo
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r api_yamdb/requirements.txt

      - name: Testing
        run: |
          python -m flake8
